const KASANE_CONTENTS = [
  {
    contentId: "classic_001",
    type: "classic",
    title: "枕草子",
    author: "清少納言",
    fragment: "春はあけぼの。",
    shortComment: "一日のはじまりに、淡い光を重ねる一節。",
    tags: ["春", "光", "透明感", "余白"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "平安時代",
    themeGroup: "春・桜・光",
    shareText: "春はあけぼの。誰かの朝に、そっと重ねたい一節。",
    imagePath: ""
  },
  {
    contentId: "classic_002",
    type: "classic",
    title: "方丈記",
    author: "鴨長明",
    fragment: "ゆく河の流れは絶えずして、しかももとの水にあらず。",
    shortComment: "流れ続ける時間に、静かな無常を重ねる一節。",
    tags: ["無常", "静けさ", "余白", "旅"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "鎌倉時代",
    themeGroup: "旅・無常・余白",
    shareText: "ゆく河の流れは絶えずして。静かな無常に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_003",
    type: "classic",
    title: "徒然草",
    author: "吉田兼好",
    fragment: "花は盛りに、月は隈なきをのみ見るものかは。",
    shortComment: "満ちきらないものの中に、美しさを見つける一節。",
    tags: ["月", "儚い", "余白", "静けさ"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "鎌倉時代",
    themeGroup: "青・夜・月",
    shareText: "花は盛りに。満ちきらないものに、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_004",
    type: "classic",
    title: "万葉集",
    author: "額田王",
    fragment: "あかねさす紫野行き標野行き",
    shortComment: "色と野の広がりに、遠いまなざしを重ねる一節。",
    tags: ["光", "旅", "和風", "凛とした"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "飛鳥時代",
    themeGroup: "春・桜・光",
    shareText: "あかねさす紫野行き。遠いまなざしに、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_005",
    type: "classic",
    title: "伊勢物語",
    author: "作者不詳",
    fragment: "月やあらぬ\n春や昔の春ならぬ",
    shortComment: "変わらない景色に、変わってしまった心を重ねる一節。",
    tags: ["月", "儚い", "夜", "孤独"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "平安時代",
    themeGroup: "青・夜・月",
    shareText: "月やあらぬ、春や昔の春ならぬ。変わらない景色に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "painting_001",
    type: "painting",
    title: "睡蓮",
    author: "クロード・モネ",
    fragment: "水面にひらく、静かな光。",
    shortComment: "水と光のあわいに、静かな気配を重ねる一枚。",
    tags: ["透明感", "青", "静けさ", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1906年頃",
    themeGroup: "旅・無常・余白",
    shareText: "水面にひらく、静かな光。誰かの気配を、水と光の中に重ねる。",
    imagePath: "assets/images/monet-water-lilies.jpg"
  },
  {
    contentId: "painting_002",
    type: "painting",
    title: "真珠の耳飾りの少女",
    author: "ヨハネス・フェルメール",
    fragment: "ふり返るまなざしの中に、静けさが残る。",
    shortComment: "言葉になる前のまなざしに、誰かの気配を重ねる一枚。",
    tags: ["静けさ", "青", "凛とした", "透明感"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1665年頃",
    themeGroup: "孤独・祈り・静けさ",
    shareText: "ふり返るまなざしの中に、静けさが残る。誰かの気配を重ねる。",
    imagePath: "assets/images/vermeer-girl-with-pearl-earring.jpg"
  },
  {
    contentId: "painting_003",
    type: "painting",
    title: "星月夜",
    author: "フィンセント・ファン・ゴッホ",
    fragment: "夜空が、静かに渦を巻いている。",
    shortComment: "深い青の夜に、祈りのような光を重ねる一枚。",
    tags: ["夜", "月", "祈り", "青"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1889年",
    themeGroup: "青・夜・月",
    shareText: "夜空が、静かに渦を巻いている。深い青の夜に、誰かの気配を重ねる。",
    imagePath: "assets/images/vangogh-starry-night.jpg"
  },
  {
    contentId: "painting_004",
    type: "painting",
    title: "黄道十二宮",
    author: "アルフォンス・ミュシャ",
    fragment: "装飾の中に、凛とした横顔が浮かぶ。",
    shortComment: "華やかな線の奥に、静かな強さを重ねる一枚。",
    tags: ["祈り", "凛とした", "和風", "光"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1896年",
    themeGroup: "旅・無常・余白",
    shareText: "装飾の中に、凛とした横顔が浮かぶ。誰かの強さを重ねる。",
    imagePath: "assets/images/mucha-zodiac.jpg"
  },
  {
    contentId: "painting_005",
    type: "painting",
    title: "真珠の女",
    author: "カミーユ・コロー",
    fragment: "ひかえめな光の中に、静かな輪郭が残る。",
    shortComment: "派手ではない美しさに、沈黙の気配を重ねる一枚。",
    tags: ["静けさ", "余白", "凛とした", "孤独"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1868年頃",
    themeGroup: "孤独・祈り・静けさ",
    shareText: "ひかえめな光の中に、静かな輪郭が残る。沈黙の気配を重ねる。",
    imagePath: "assets/images/corot-woman-with-a-pearl.jpg"
  },
  {
    contentId: "poem_001",
    type: "poem",
    title: "雨ニモマケズ",
    author: "宮沢賢治",
    fragment: "雨ニモマケズ\n風ニモマケズ",
    shortComment: "静かな強さに、祈りのような輪郭を重ねる一節。",
    tags: ["雨", "祈り", "凛とした", "静けさ"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1931年",
    themeGroup: "孤独・祈り・静けさ",
    shareText: "雨ニモマケズ、風ニモマケズ。静かな強さに、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_002",
    type: "poem",
    title: "汚れつちまつた悲しみに……",
    author: "中原中也",
    fragment: "汚れつちまつた悲しみに",
    shortComment: "夜の底に沈むような、静かな悲しみの一節。",
    tags: ["孤独", "夜", "儚い", "静けさ"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1934年",
    themeGroup: "孤独・祈り・静けさ",
    shareText: "汚れつちまつた悲しみに。夜の底に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_003",
    type: "poem",
    title: "私と小鳥と鈴と",
    author: "金子みすゞ",
    fragment: "みんなちがって、みんないい。",
    shortComment: "それぞれの違いに、やわらかな光を重ねる一節。",
    tags: ["光", "祈り", "余白", "透明感"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1920年代",
    themeGroup: "春・桜・光",
    shareText: "みんなちがって、みんないい。やわらかな光に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_004",
    type: "poem",
    title: "素朴な琴",
    author: "八木重吉",
    fragment: "この明るさのなかへ\nひとつの素朴な琴をおけば",
    shortComment: "明るさの中に、透明な音の気配を重ねる一節。",
    tags: ["光", "祈り", "透明感", "静けさ"],
    defaultColor: { name: "胡粉色", hex: "#FFFFFC" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1925年頃",
    themeGroup: "春・桜・光",
    shareText: "この明るさのなかへ、ひとつの素朴な琴をおけば。誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_005",
    type: "poem",
    title: "月に吠える",
    author: "萩原朔太郎",
    fragment: "竹が生え、\n竹が生え、",
    shortComment: "月の下に立ちのぼる、不穏で静かな気配の一節。",
    tags: ["月", "孤独", "夜", "儚い"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "public_domain",
    sourceUrl: "",
    licenseNote: "パブリックドメイン",
    period: "1917年",
    themeGroup: "青・夜・月",
    shareText: "竹が生え、竹が生え、。月の下の静かな気配に、誰かを重ねる。",
    imagePath: ""
  }
];

const KASANE_COLORS = [
  { name: "桜色",  basic: "ピンク",  hex: "#FDEFF2" },
  { name: "薄紅",  basic: "ピンク",  hex: "#FADCE0" },
  { name: "生成色", basic: "ベージュ", hex: "#FBFAF5" },
  { name: "胡粉色", basic: "白",     hex: "#FFFFFC" },
  { name: "銀鼠",  basic: "グレー",  hex: "#AFAFB0" },
  { name: "墨色",  basic: "黒",     hex: "#2B2B2B" },
  { name: "瑠璃色", basic: "青",     hex: "#1E50A2" },
  { name: "浅葱色", basic: "青緑",   hex: "#00A3AF" },
  { name: "藤色",  basic: "紫",     hex: "#BBBCDE" },
  { name: "青磁",  basic: "青緑",   hex: "#A8C8B9" },
  { name: "紅色",  basic: "赤",     hex: "#C22047" },
  { name: "朱色",  basic: "赤橙",   hex: "#EB6101" },
  { name: "山吹色", basic: "黄",     hex: "#F8B500" },
  { name: "若草色", basic: "緑",     hex: "#C3D825" },
  { name: "常磐色", basic: "緑",     hex: "#007B43" },
  { name: "空色",  basic: "水色",   hex: "#A0D8EF" },
  { name: "藍色",  basic: "青",     hex: "#165E83" },
  { name: "菫色",  basic: "紫",     hex: "#7058A3" },
  { name: "葡萄色", basic: "紫",     hex: "#522F60" },
  { name: "煤竹色", basic: "茶",     hex: "#5D5245" }
];
