const KASANE_CONTENTS = [
  {
    contentId: "classic_001",
    type: "classic",
    title: "方丈記",
    author: "鴨長明",
    fragment: "ゆく河の流れは絶えずして、しかももとの水にあらず。",
    shortComment: "流れ続ける時間に、静かな無常を重ねる一節。",
    tags: ["無常", "静けさ", "余白", "旅"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000196/files/975_15935.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "鎌倉時代",
    learn: {
      intro: "『方丈記』は、鎌倉時代の随筆です。災害や世の移り変わりを見つめながら、小さな住まいで生きる感覚まで静かに書き残しています。",
      point: "冒頭の一文は、変わらないように見えるものほど、実は少しずつ変わっていることを思い出させます。きれいなのに、少しだけ胸が冷える断片です。",
      tips: "題名の「方丈」は、約三メートル四方ほどの小さな庵のこと。この人、スケールの大きい無常を語りながら、暮らしのサイズ感はかなりミニマルです。",
      sourceLabel: "青空文庫で読む"
    },
    themeGroup: "旅・無常・余白",
    shareText: "ゆく河の流れは絶えずして。静かな無常に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_002",
    type: "classic",
    title: "竹取物語",
    author: "作者不詳",
    fragment: "今は昔、竹取の翁といふものありけり。",
    shortComment: "光る竹から始まる、遠い物語の入口。",
    tags: ["光", "和風", "月", "物語"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/001072/files/48310_42692.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "平安時代初期成立とされる",
    themeGroup: "月・光・物語",
    shareText: "光る竹から始まる物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_003",
    type: "classic",
    title: "更級日記",
    author: "菅原孝標女",
    fragment: "あづま路の道の果てよりも、なほ奥つ方に生ひ出でたる人。",
    shortComment: "遠い土地から物語へ憧れる、静かな出発点。",
    tags: ["旅", "憧れ", "物語", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000133/card706.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "平安時代",
    themeGroup: "旅・憧れ・物語",
    shareText: "遠い道の果てから、物語への憧れを重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_004",
    type: "classic",
    title: "土佐日記",
    author: "紀貫之",
    fragment: "男もすなる日記といふものを、女もしてみむとてするなり。",
    shortComment: "視点を少しずらすだけで、世界が書き換わる一節。",
    tags: ["旅", "ことば", "余白", "日記"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000155/files/832_16016.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "平安時代",
    themeGroup: "旅・ことば・日記",
    shareText: "視点を変える一文に、書くことの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_005",
    type: "classic",
    title: "現代語訳 徒然草",
    author: "兼好法師 / 佐藤春夫訳",
    fragment: "つれづれなるままに、日暮し、硯にむかひて。",
    shortComment: "ひとりの時間に、思いの断片を重ねる一節。",
    tags: ["余白", "静けさ", "ことば", "孤独"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/002238/files/61411_78314.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "鎌倉時代 / 訳は近代",
    themeGroup: "余白・思索・静けさ",
    shareText: "ひとりの時間に、静かな思索を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_006",
    type: "classic",
    title: "源氏物語 桐壺",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "紫のかがやく花と日の光思ひあはざる",
    shortComment: "『源氏物語』桐壺に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5016.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "桐壺の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_007",
    type: "classic",
    title: "源氏物語 帚木",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "雨夜の品定め。",
    shortComment: "『源氏物語』帚木に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5017.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "帚木の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_008",
    type: "classic",
    title: "源氏物語 空蝉",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "空蝉の身をかへてける木のもとに",
    shortComment: "『源氏物語』空蝉に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5018.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "空蝉の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_009",
    type: "classic",
    title: "源氏物語 夕顔",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "夕顔の花のひらめきに、夏の宵が残る。",
    shortComment: "『源氏物語』夕顔に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5019.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "夕顔の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_010",
    type: "classic",
    title: "源氏物語 若紫",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "雀の子を犬君が逃がしつる。",
    shortComment: "『源氏物語』若紫に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5020.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "若紫の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_011",
    type: "classic",
    title: "源氏物語 末摘花",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "末摘花の名に、紅の余韻が残る。",
    shortComment: "『源氏物語』末摘花に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5021.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "末摘花の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_012",
    type: "classic",
    title: "源氏物語 紅葉賀",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "紅葉の宴に、秋の色が重なる。",
    shortComment: "『源氏物語』紅葉賀に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5022.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "紅葉賀の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_013",
    type: "classic",
    title: "源氏物語 花宴",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "花の宴の夜に、香りと気配がまじる。",
    shortComment: "『源氏物語』花宴に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5023.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "花宴の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_014",
    type: "classic",
    title: "源氏物語 葵",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "葵の上に、静かな影が差す。",
    shortComment: "『源氏物語』葵に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5024.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "葵の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_015",
    type: "classic",
    title: "源氏物語 榊",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "榊の葉に、別れの祈りを重ねる。",
    shortComment: "『源氏物語』榊に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5025.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "榊の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_016",
    type: "classic",
    title: "源氏物語 花散里",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "花散里に、過ぎた春の余韻が残る。",
    shortComment: "『源氏物語』花散里に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5026.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "花散里の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_017",
    type: "classic",
    title: "源氏物語 須磨",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "須磨には、いとど心づくしの秋風に。",
    shortComment: "『源氏物語』須磨に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5027.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "須磨の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_018",
    type: "classic",
    title: "源氏物語 明石",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "月も入りぬるに、波の音ばかりぞ聞こゆる。",
    shortComment: "『源氏物語』明石に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5028.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "明石の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_019",
    type: "classic",
    title: "源氏物語 澪標",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "澪標の先に、行くべき道が見える。",
    shortComment: "『源氏物語』澪標に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5029.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "澪標の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_020",
    type: "classic",
    title: "源氏物語 蓬生",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "蓬生の露に、待ち続けた時間が光る。",
    shortComment: "『源氏物語』蓬生に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5030.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "蓬生の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_021",
    type: "classic",
    title: "源氏物語 関屋",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "関屋の道で、昔の面影がよみがえる。",
    shortComment: "『源氏物語』関屋に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5031.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "関屋の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_022",
    type: "classic",
    title: "源氏物語 絵合",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "絵合の場に、物語の色が競い合う。",
    shortComment: "『源氏物語』絵合に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5032.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "絵合の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_023",
    type: "classic",
    title: "源氏物語 松風",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "松風の音に、遠い心がゆれる。",
    shortComment: "『源氏物語』松風に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5033.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "松風の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_024",
    type: "classic",
    title: "源氏物語 薄雲",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "薄雲の向こうに、別れの空がひろがる。",
    shortComment: "『源氏物語』薄雲に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5034.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "薄雲の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_025",
    type: "classic",
    title: "源氏物語 朝顔",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "朝顔の花に、届かない思いを重ねる。",
    shortComment: "『源氏物語』朝顔に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5035.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "朝顔の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_026",
    type: "classic",
    title: "源氏物語 乙女",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "乙女の季節に、若い光が満ちる。",
    shortComment: "『源氏物語』乙女に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5036.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "乙女の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_027",
    type: "classic",
    title: "源氏物語 玉鬘",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "玉鬘の名に、隠れていた運命がほどける。",
    shortComment: "『源氏物語』玉鬘に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5037.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "玉鬘の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_028",
    type: "classic",
    title: "源氏物語 初音",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "初音の春に、やわらかな便りが届く。",
    shortComment: "『源氏物語』初音に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5038.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "初音の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_029",
    type: "classic",
    title: "源氏物語 胡蝶",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "胡蝶の舞に、春の華やぎが漂う。",
    shortComment: "『源氏物語』胡蝶に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5039.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "胡蝶の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "classic_030",
    type: "classic",
    title: "源氏物語 蛍",
    author: "紫式部 / 与謝野晶子訳",
    fragment: "蛍の光に、夜の思いが浮かぶ。",
    shortComment: "『源氏物語』蛍に、物語の気配を重ねる一節。",
    tags: ["物語", "宮廷", "余白", "和風"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000052/card5040.html",
    licenseNote: "青空文庫掲載の与謝野晶子訳本文。",
    period: "平安時代 / 訳は近代",
    themeGroup: "宮廷・物語・余白",
    shareText: "蛍の物語に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_001",
    type: "poem",
    title: "雨ニモマケズ",
    author: "宮沢賢治",
    fragment: "雨ニモマケズ\n風ニモマケズ",
    shortComment: "静かな強さに、祈りのような輪郭を重ねる一節。",
    tags: ["雨", "祈り", "凛とした", "静けさ"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/45630_23908.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1931年",
    themeGroup: "祈り・強さ・雨",
    shareText: "雨ニモマケズ、風ニモマケズ。静かな強さに、誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_002",
    type: "poem",
    title: "永訣の朝",
    author: "宮沢賢治",
    fragment: "あめゆじゅとてちてけんじゃ",
    shortComment: "雪の朝に残る、痛いほどやさしい声。",
    tags: ["雪", "祈り", "別れ", "透明感"],
    defaultColor: { name: "胡粉色", hex: "#FFFFFC" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/1058_15403.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1922年頃",
    themeGroup: "雪・別れ・祈り",
    shareText: "雪の朝の声に、忘れられない誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_003",
    type: "poem",
    title: "春と修羅",
    author: "宮沢賢治",
    fragment: "わたくしといふ現象は",
    shortComment: "自分という存在を、光と風の中にほどく一節。",
    tags: ["光", "風", "透明感", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/1058_15403.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1924年",
    themeGroup: "光・風・自己",
    shareText: "わたくしという現象に、透明な気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_004",
    type: "poem",
    title: "告別",
    author: "宮沢賢治",
    fragment: "おまへはもうさうしてたづねることもない",
    shortComment: "別れのあとに残る、静かな問いかけ。",
    tags: ["別れ", "静けさ", "祈り", "余白"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/1058_15403.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1920年代",
    themeGroup: "別れ・祈り・余白",
    shareText: "別れのあとに残る問いに、誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_005",
    type: "poem",
    title: "原体剣舞連",
    author: "宮沢賢治",
    fragment: "dah-dah-dah-dah-dah-sko-dah-dah",
    shortComment: "踊りと声が、大地の熱を呼び起こす一節。",
    tags: ["踊り", "音", "土", "勢い"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/1058_15403.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1922年頃",
    themeGroup: "踊り・音・大地",
    shareText: "大地を踏む音に、熱い気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_006",
    type: "poem",
    title: "青森挽歌",
    author: "宮沢賢治",
    fragment: "こんなやみよののはらのなかをゆくときは",
    shortComment: "闇の野を進む列車に、深い別れを重ねる一節。",
    tags: ["夜", "旅", "別れ", "祈り"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000081/files/1058_15403.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1923年頃",
    themeGroup: "夜・旅・別れ",
    shareText: "闇を行く列車に、遠い誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_007",
    type: "poem",
    title: "汚れつちまつた悲しみに……",
    author: "中原中也",
    fragment: "汚れつちまつた悲しみに",
    shortComment: "夜の底に沈むような、静かな悲しみの一節。",
    tags: ["孤独", "夜", "儚い", "静けさ"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000026/files/894_28272.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1934年",
    themeGroup: "孤独・悲しみ・夜",
    shareText: "汚れつちまつた悲しみに。夜の底に、誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_008",
    type: "poem",
    title: "サーカス",
    author: "中原中也",
    fragment: "ゆあーん ゆよーん ゆやゆよん",
    shortComment: "揺れる音だけで、寂しさが立ち上がる一節。",
    tags: ["音", "孤独", "夜", "不思議"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000026/files/894_28272.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1934年",
    themeGroup: "音・孤独・夜",
    shareText: "ゆあーん、ゆよーん。揺れる音に、誰かの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_009",
    type: "poem",
    title: "帰郷",
    author: "中原中也",
    fragment: "柱も庭も乾いてゐる",
    shortComment: "帰ってきた場所にある、からっぽの静けさ。",
    tags: ["帰郷", "孤独", "静けさ", "余白"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000026/files/894_28272.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1930年代",
    themeGroup: "帰郷・孤独・余白",
    shareText: "乾いた庭の静けさに、帰れない誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_010",
    type: "poem",
    title: "一つのメルヘン",
    author: "中原中也",
    fragment: "秋の夜は、はるかの彼方に",
    shortComment: "遠く澄んだ夜に、物語のような寂しさを重ねる一節。",
    tags: ["秋", "夜", "孤独", "物語"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000026/files/219_33152.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1930年代",
    themeGroup: "秋・夜・物語",
    shareText: "秋の夜の彼方に、誰かの物語を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_011",
    type: "poem",
    title: "湖上",
    author: "中原中也",
    fragment: "ポッカリ月が出ましたら、",
    shortComment: "水面に出た月へ、寂しさと親しさを重ねる一節。",
    tags: ["月", "水", "夜", "孤独"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000026/files/894_28272.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1934年",
    themeGroup: "月・水・夜",
    shareText: "湖上の月に、静かな誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_012",
    type: "poem",
    title: "月に吠える",
    author: "萩原朔太郎",
    fragment: "竹が生え、\n竹が生え、",
    shortComment: "月の下に立ちのぼる、不穏で静かな気配の一節。",
    tags: ["月", "孤独", "夜", "儚い"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000067/files/859_21656.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1917年",
    themeGroup: "月・夜・孤独",
    shareText: "竹が生え、竹が生え。月の下の気配に、誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_013",
    type: "poem",
    title: "地面の底の病気の顔",
    author: "萩原朔太郎",
    fragment: "地面の底に顔があらはれ、",
    shortComment: "見えない底から、心の影が浮かび上がる一節。",
    tags: ["孤独", "夜", "不穏", "影"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000067/files/859_21656.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1917年",
    themeGroup: "影・孤独・不穏",
    shareText: "地面の底から浮かぶ顔に、心の影を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_014",
    type: "poem",
    title: "旅上",
    author: "萩原朔太郎",
    fragment: "ふらんすへ行きたしと思へども",
    shortComment: "行けない場所への憧れに、旅の心を重ねる一節。",
    tags: ["旅", "憧れ", "孤独", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000067/files/53597_44239.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "大正期",
    themeGroup: "旅・憧れ・孤独",
    shareText: "行けない場所への憧れに、誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_015",
    type: "poem",
    title: "猫",
    author: "萩原朔太郎",
    fragment: "まつくろけの猫が二匹、",
    shortComment: "夜の輪郭をすべるような、不思議な気配。",
    tags: ["夜", "不思議", "孤独", "影"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000067/files/859_21656.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "大正期",
    themeGroup: "夜・不思議・孤独",
    shareText: "黒い影の気配に、夜の誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_016",
    type: "poem",
    title: "素朴な琴",
    author: "八木重吉",
    fragment: "この明るさのなかへ\nひとつの素朴な琴をおけば",
    shortComment: "明るさの中に、透明な音の気配を重ねる一節。",
    tags: ["光", "祈り", "透明感", "静けさ"],
    defaultColor: { name: "胡粉色", hex: "#FFFFFC" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000013/files/542_42320.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1920年代",
    themeGroup: "光・音・祈り",
    shareText: "明るさの中の琴に、透明な気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_017",
    type: "poem",
    title: "響",
    author: "八木重吉",
    fragment: "秋はあかるくなりきった",
    shortComment: "明るさの奥にある、しずかな響きを見つめる一節。",
    tags: ["秋", "光", "静けさ", "音"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000013/files/542_42320.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1920年代",
    themeGroup: "秋・光・音",
    shareText: "秋の明るさの奥に、しずかな響きを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_018",
    type: "poem",
    title: "霧",
    author: "八木重吉",
    fragment: "霧がみなぎっている",
    shortComment: "霧の中で、心だけが少し高ぶっていく一節。",
    tags: ["霧", "朝", "静けさ", "透明感"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000013/files/542_42320.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1920年代",
    themeGroup: "霧・朝・静けさ",
    shareText: "霧の気配に、つつましい心の高ぶりを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_019",
    type: "poem",
    title: "お化け",
    author: "八木重吉",
    fragment: "冬は\n夜になると",
    shortComment: "冬の夜にふっと現れる、薄い不安の気配。",
    tags: ["冬", "夜", "不思議", "孤独"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000013/files/542_42320.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1920年代",
    themeGroup: "冬・夜・不思議",
    shareText: "冬の夜の薄い不安に、誰かの影を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_020",
    type: "poem",
    title: "優しき歌",
    author: "立原道造",
    fragment: "灰色に ひとりぼつちに",
    shortComment: "やさしい朝の中に、ひとりの影が残る一節。",
    tags: ["朝", "孤独", "やさしさ", "余白"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000011/files/899_27483.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1930年代",
    themeGroup: "朝・孤独・やさしさ",
    shareText: "灰色のひとりぼっちに、やさしい朝を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_021",
    type: "poem",
    title: "暁と夕の詩",
    author: "立原道造",
    fragment: "朝やけよ！早く来い",
    shortComment: "夜の向こうから朝を呼ぶ、切実な一節。",
    tags: ["朝", "夜明け", "祈り", "光"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000011/files/9_20331.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1930年代",
    themeGroup: "朝・夜明け・祈り",
    shareText: "朝やけを呼ぶ声に、夜明けの気配を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_022",
    type: "poem",
    title: "萱草に寄す",
    author: "立原道造",
    fragment: "ゆさぶれ 青い梢を",
    shortComment: "青い梢に、若い感情の揺れを重ねる一節。",
    tags: ["青", "風", "若さ", "透明感"],
    defaultColor: { name: "浅葱色", hex: "#00A3AF" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000011/files/889_20333.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1930年代",
    themeGroup: "青・風・若さ",
    shareText: "青い梢の揺れに、若い誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_023",
    type: "poem",
    title: "邪宗門",
    author: "北原白秋",
    fragment: "ここ過ぎて 曲節の悩みのむれに、",
    shortComment: "装飾的な言葉の奥に、甘い不穏さを重ねる一節。",
    tags: ["祈り", "不穏", "装飾", "夜"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000106/files/4850_13918.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1909年",
    themeGroup: "装飾・祈り・不穏",
    shareText: "装飾的な言葉の奥に、誰かの影を重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_024",
    type: "poem",
    title: "思ひ出",
    author: "北原白秋",
    fragment: "過ぎし日の思ひ出は、",
    shortComment: "記憶の底に沈む、淡い色のような一節。",
    tags: ["記憶", "儚い", "余白", "光"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000106/files/2415_45802.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1911年",
    themeGroup: "記憶・儚さ・光",
    shareText: "過ぎし日の思い出に、淡い誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_025",
    type: "poem",
    title: "道程",
    author: "高村光太郎",
    fragment: "僕の前に道はない",
    shortComment: "まだない道を、自分の足で作っていく一節。",
    tags: ["道", "凛とした", "光", "意志"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/001168/files/59185_75168.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1914年",
    themeGroup: "道・意志・光",
    shareText: "まだない道に、まっすぐな誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_026",
    type: "poem",
    title: "智恵子抄 あどけない話",
    author: "高村光太郎",
    fragment: "智恵子は東京に空が無いといふ、",
    shortComment: "空を探す言葉に、失われた広さを重ねる一節。",
    tags: ["空", "青", "孤独", "透明感"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/001168/files/46669_25695.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1928年",
    themeGroup: "空・青・孤独",
    shareText: "東京にない空に、遠い誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_027",
    type: "poem",
    title: "智恵子抄 レモン哀歌",
    author: "高村光太郎",
    fragment: "そんなにもあなたはレモンを待つてゐた",
    shortComment: "死のそばにある、鮮やかなレモンの光。",
    tags: ["光", "別れ", "祈り", "黄色"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/001168/files/46669_25695.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1939年",
    themeGroup: "別れ・光・祈り",
    shareText: "レモンの光に、忘れられない誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_028",
    type: "poem",
    title: "初恋",
    author: "島崎藤村",
    fragment: "まだあげ初めし前髪の",
    shortComment: "若い記憶のはじまりに、淡い光を重ねる一節。",
    tags: ["恋", "春", "儚い", "光"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000158/files/1508_18509.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "1897年",
    themeGroup: "恋・記憶・春",
    shareText: "初恋の淡い光に、若い誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_029",
    type: "poem",
    title: "晶子詩篇全集",
    author: "与謝野晶子",
    fragment: "君さらば巫山の春のひと夜妻",
    shortComment: "熱を帯びた言葉に、まっすぐな心を重ねる一節。",
    tags: ["恋", "祈り", "凛とした", "春"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000885/files/2557_15784.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "明治〜昭和期",
    themeGroup: "恋・祈り・言葉",
    shareText: "熱のある言葉に、誰かへの祈りを重ねる。",
    imagePath: ""
  },
  {
    contentId: "poem_030",
    type: "poem",
    title: "晶子詩篇全集拾遺",
    author: "与謝野晶子",
    fragment: "ああ皐月仏蘭西の野は火の色す",
    shortComment: "遠い野の色に、旅する心を重ねる一節。",
    tags: ["旅", "光", "色", "憧れ"],
    defaultColor: { name: "浅葱色", hex: "#00A3AF" },
    source: "青空文庫",
    sourceUrl: "https://www.aozora.gr.jp/cards/000885/files/2558_15785.html",
    licenseNote: "青空文庫掲載のパブリックドメイン本文。",
    period: "明治〜昭和期",
    themeGroup: "旅・色・憧れ",
    shareText: "遠い野の色に、旅する誰かを重ねる。",
    imagePath: ""
  },
  {
    contentId: "painting_001",
    type: "painting",
    title: "睡蓮",
    author: "クロード・モネ",
    fragment: "水面にひらく、静かな光。",
    shortComment: "水と光のあわいに、静かな気配を重ねる一枚。",
    tags: ["透明感", "青", "静けさ", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Water_Lilies_-_Google_Art_Project_(462013).jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1906年頃",
    themeGroup: "水・光・静けさ",
    shareText: "水面にひらく静かな光に、誰かの気配を重ねる。",
    imagePath: "assets/images/painting_001_monet_water_lilies.jpg"
  },
  {
    contentId: "painting_002",
    type: "painting",
    title: "真珠の耳飾りの少女",
    author: "ヨハネス・フェルメール",
    fragment: "ふり返るまなざしの中に、静けさが残る。",
    shortComment: "言葉になる前のまなざしに、誰かの気配を重ねる一枚。",
    tags: ["静けさ", "青", "凛とした", "透明感"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Girl_with_a_Pearl_Earring.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1665年頃",
    themeGroup: "まなざし・青・静けさ",
    shareText: "ふり返るまなざしに、静かな誰かを重ねる。",
    imagePath: "assets/images/painting_002_vermeer_girl_with_pearl_earring.jpg"
  },
  {
    contentId: "painting_003",
    type: "painting",
    title: "星月夜",
    author: "フィンセント・ファン・ゴッホ",
    fragment: "夜空が、静かに渦を巻いている。",
    shortComment: "深い青の夜に、祈りのような光を重ねる一枚。",
    tags: ["夜", "月", "祈り", "青"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1889年",
    learn: {
      intro: "『星月夜』は、ファン・ゴッホが南フランスのサン＝レミで描いた油彩画です。夜空の渦と村の静けさが、現実と心象のあいだにある風景のように見えます。",
      point: "星は明るいのに、画面全体にはひとりで夜を見ているような切実さがあります。青の美しさと落ち着かなさが、同時に残るところが魅力です。",
      tips: "ゴッホは弟テオへの手紙で、絵のことを何度も相談していました。孤高の画家というより、作品のそばにずっと話を聞いてほしい相手がいた人にも見えてきます。",
      sourceLabel: "画像の出典を見る"
    },
    themeGroup: "青・夜・月",
    shareText: "渦巻く夜空に、祈りのような誰かを重ねる。",
    imagePath: "assets/images/painting_003_vangogh_starry_night.jpg"
  },
  {
    contentId: "painting_004",
    type: "painting",
    title: "黄道十二宮",
    author: "アルフォンス・ミュシャ",
    fragment: "装飾の中に、凛とした横顔が浮かぶ。",
    shortComment: "華やかな線の奥に、静かな強さを重ねる一枚。",
    tags: ["装飾", "凛とした", "光", "横顔"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alphonse_Mucha_-_Zodiac.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1896年",
    themeGroup: "装飾・横顔・凛とした",
    shareText: "装飾の中の横顔に、静かな強さを重ねる。",
    imagePath: "assets/images/painting_004_mucha_zodiac.jpg"
  },
  {
    contentId: "painting_005",
    type: "painting",
    title: "真珠の女",
    author: "カミーユ・コロー",
    fragment: "ひかえめな光の中に、静かな輪郭が残る。",
    shortComment: "派手ではない美しさに、沈黙の気配を重ねる一枚。",
    tags: ["静けさ", "余白", "凛とした", "孤独"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Camille_Corot_-_Woman_with_a_Pearl.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1868年頃",
    themeGroup: "沈黙・輪郭・静けさ",
    shareText: "ひかえめな光に、沈黙の気配を重ねる。",
    imagePath: "assets/images/painting_005_corot_woman_with_pearl.jpg"
  },
  {
    contentId: "painting_006",
    type: "painting",
    title: "モナ・リザ",
    author: "レオナルド・ダ・ヴィンチ",
    fragment: "微笑みは、まだ言葉にならない。",
    shortComment: "説明しきれない表情に、長い沈黙を重ねる一枚。",
    tags: ["まなざし", "静けさ", "謎", "余白"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1503年頃-1519年頃",
    themeGroup: "まなざし・謎・沈黙",
    shareText: "言葉にならない微笑みに、誰かの気配を重ねる。",
    imagePath: "assets/images/painting_006_da_vinci_mona_lisa.jpg"
  },
  {
    contentId: "painting_007",
    type: "painting",
    title: "ヴィーナスの誕生",
    author: "サンドロ・ボッティチェリ",
    fragment: "海から、やわらかな神話が立ち上がる。",
    shortComment: "淡い風と海に、美のはじまりを重ねる一枚。",
    tags: ["海", "神話", "風", "透明感"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_046.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1485年頃",
    themeGroup: "海・神話・美",
    shareText: "海から立ち上がる神話に、誰かの美しさを重ねる。",
    imagePath: "assets/images/painting_007_botticelli_birth_of_venus.jpg"
  },
  {
    contentId: "painting_008",
    type: "painting",
    title: "春（プリマヴェーラ）",
    author: "サンドロ・ボッティチェリ",
    fragment: "花と風が、春の奥でひそかに動く。",
    shortComment: "装飾的な春に、祝福の気配を重ねる一枚。",
    tags: ["春", "花", "神話", "祝福"],
    defaultColor: { name: "桜色", hex: "#FDEFF2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Botticelli-primavera.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1470年代後半-1480年代前半",
    themeGroup: "春・花・神話",
    shareText: "花と風の春に、祝福される誰かを重ねる。",
    imagePath: "assets/images/painting_008_botticelli_primavera.jpg"
  },
  {
    contentId: "painting_009",
    type: "painting",
    title: "オフィーリア",
    author: "ジョン・エヴァレット・ミレー",
    fragment: "花に囲まれて、沈黙が水面にひろがる。",
    shortComment: "美しさと悲しみが同じ水面に浮かぶ一枚。",
    tags: ["花", "水", "儚い", "孤独"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1851-1852年",
    themeGroup: "花・水・儚さ",
    shareText: "水面の沈黙に、儚い誰かを重ねる。",
    imagePath: "assets/images/painting_009_millais_ophelia.jpg"
  },
  {
    contentId: "painting_010",
    type: "painting",
    title: "接吻",
    author: "グスタフ・クリムト",
    fragment: "金色の装飾の中で、ふたりの時間が止まる。",
    shortComment: "華やかさの中に閉じ込められた、静かな親密さ。",
    tags: ["装飾", "恋", "光", "余白"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1907-1908年",
    themeGroup: "装飾・恋・光",
    shareText: "金色の時間に、親密な誰かを重ねる。",
    imagePath: "assets/images/painting_010_klimt_the_kiss.jpg"
  },
  {
    contentId: "painting_011",
    type: "painting",
    title: "アデーレ・ブロッホ＝バウアーの肖像 I",
    author: "グスタフ・クリムト",
    fragment: "金の奥で、まなざしだけが静かに残る。",
    shortComment: "装飾と沈黙がせめぎ合う、強い肖像。",
    tags: ["装飾", "まなざし", "凛とした", "光"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gustav_Klimt,_1907,_Adele_Bloch-Bauer_I,_Neue_Galerie_New_York.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1907年",
    themeGroup: "装飾・肖像・まなざし",
    shareText: "金の奥のまなざしに、強い誰かを重ねる。",
    imagePath: "assets/images/painting_011_klimt_adele_bloch_bauer.jpg"
  },
  {
    contentId: "painting_012",
    type: "painting",
    title: "夜のカフェテラス",
    author: "フィンセント・ファン・ゴッホ",
    fragment: "夜の青に、灯りが小さく息をしている。",
    shortComment: "にぎわいの手前にある、ひとりの夜を重ねる一枚。",
    tags: ["夜", "光", "青", "街"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent-van-gogh-cafe-terrace-on-the-place-du-forum-arles-at-night-the.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1888年",
    themeGroup: "夜・街・光",
    shareText: "夜の灯りに、ひとりの誰かを重ねる。",
    imagePath: "assets/images/painting_012_vangogh_cafe_terrace_at_night.jpg"
  },
  {
    contentId: "painting_013",
    type: "painting",
    title: "ローヌ川の星月夜",
    author: "フィンセント・ファン・ゴッホ",
    fragment: "川に星が落ちて、夜が静かに揺れる。",
    shortComment: "水面の星に、遠い祈りを重ねる一枚。",
    tags: ["星", "夜", "川", "青"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1888年",
    themeGroup: "星・夜・川",
    shareText: "川に揺れる星に、遠い誰かを重ねる。",
    imagePath: "assets/images/painting_013_vangogh_starry_night_over_rhone.jpg"
  },
  {
    contentId: "painting_014",
    type: "painting",
    title: "ひまわり",
    author: "フィンセント・ファン・ゴッホ",
    fragment: "黄色い花が、まっすぐに光を抱えている。",
    shortComment: "強い明るさの奥にある、少し痛いほどの生命感。",
    tags: ["花", "光", "黄色", "凛とした"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1888年",
    themeGroup: "花・光・生命感",
    shareText: "ひまわりの光に、まっすぐな誰かを重ねる。",
    imagePath: "assets/images/painting_014_vangogh_sunflowers.jpg"
  },
  {
    contentId: "painting_015",
    type: "painting",
    title: "笛を吹く少年",
    author: "エドゥアール・マネ",
    fragment: "赤と黒の輪郭が、静かに立っている。",
    shortComment: "簡潔な構図の中に、凛とした気配を重ねる一枚。",
    tags: ["凛とした", "余白", "赤", "静けさ"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Manet,_Edouard_-_Young_Flautist,_or_The_Fifer,_1866_(2).jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1866年",
    themeGroup: "余白・輪郭・凛とした",
    shareText: "静かに立つ輪郭に、凛とした誰かを重ねる。",
    imagePath: "assets/images/painting_015_manet_fifer.jpg"
  },
  {
    contentId: "painting_016",
    type: "painting",
    title: "ムーラン・ド・ラ・ギャレットの舞踏会",
    author: "ピエール＝オーギュスト・ルノワール",
    fragment: "木漏れ日の下で、時間がやわらかく踊る。",
    shortComment: "にぎやかさの中に、やさしい光を重ねる一枚。",
    tags: ["光", "踊り", "春", "祝福"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Renoir,_Pierre-Auguste_-_Dance_at_Le_Moulin_de_la_Galette,_1876.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1876年",
    themeGroup: "光・祝祭・踊り",
    shareText: "木漏れ日の踊りに、やわらかな誰かを重ねる。",
    imagePath: "assets/images/painting_016_renoir_moulin_de_la_galette.jpg"
  },
  {
    contentId: "painting_017",
    type: "painting",
    title: "神奈川沖浪裏",
    author: "葛飾北斎",
    fragment: "波が、空まで届きそうに立ち上がる。",
    shortComment: "荒い波の向こうに、遠い富士の静けさを重ねる一枚。",
    tags: ["海", "和風", "青", "凛とした"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_Wave_off_Kanagawa2.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1831年頃",
    themeGroup: "海・波・和風",
    shareText: "立ち上がる波に、強い誰かを重ねる。",
    imagePath: "assets/images/painting_017_hokusai_great_wave.jpg"
  },
  {
    contentId: "painting_018",
    type: "painting",
    title: "凱風快晴",
    author: "葛飾北斎",
    fragment: "赤い富士が、朝の空に静かに立つ。",
    shortComment: "簡潔な色面に、晴れやかな強さを重ねる一枚。",
    tags: ["富士", "朝", "和風", "光"],
    defaultColor: { name: "薄紅", hex: "#FADCE0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Katsushika_Hokusai_-_Fine_Wind,_Clear_Morning_(Gaifū_kaisei)_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1831年頃",
    themeGroup: "富士・朝・光",
    shareText: "赤い富士の朝に、晴れやかな誰かを重ねる。",
    imagePath: "assets/images/painting_018_hokusai_red_fuji.jpg"
  },
  {
    contentId: "painting_019",
    type: "painting",
    title: "雨、蒸気、速度",
    author: "ジョゼフ・マロード・ウィリアム・ターナー",
    fragment: "雨の中を、光と速度が駆け抜ける。",
    shortComment: "近代の気配を、霞む空気とともに重ねる一枚。",
    tags: ["雨", "光", "速度", "近代"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Turner_-_Rain,_Steam_and_Speed_-_National_Gallery_file.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1844年",
    themeGroup: "雨・光・速度",
    shareText: "雨と速度の中に、進んでいく誰かを重ねる。",
    imagePath: "assets/images/painting_019_turner_rain_steam_speed.jpg"
  },
  {
    contentId: "painting_020",
    type: "painting",
    title: "見返り美人図",
    author: "菱川師宣",
    fragment: "振り返る一瞬に、時間が止まる。",
    shortComment: "背中とまなざしの間に、余韻を重ねる一枚。",
    tags: ["和風", "まなざし", "余白", "凛とした"],
    defaultColor: { name: "藤色", hex: "#BBBCDE" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hishikawa_Moronobu_-_Beauty_Looking_Back_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "17世紀後半",
    themeGroup: "和風・まなざし・余韻",
    shareText: "振り返る一瞬に、誰かの余韻を重ねる。",
    imagePath: "assets/images/painting_020_moronobu_beauty_looking_back.jpg"
  },
  {
    contentId: "painting_021",
    type: "painting",
    title: "富嶽三十六景 甲州石班沢",
    author: "葛飾北斎",
    fragment: "水辺の線に、暮らしと富士が重なる。",
    shortComment: "日常の手前にある、大きな景色を重ねる一枚。",
    tags: ["水", "富士", "和風", "余白"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kajikazawa_in_Kai_province.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1830年代",
    themeGroup: "水・富士・暮らし",
    shareText: "水辺の暮らしに、大きな景色を重ねる。",
    imagePath: "assets/images/painting_021_hokusai_koshu_kajikazawa.jpg"
  },
  {
    contentId: "painting_022",
    type: "painting",
    title: "青い馬 I",
    author: "フランツ・マルク",
    fragment: "青い馬が、静かに内側を見つめている。",
    shortComment: "非現実の青に、澄んだ孤独を重ねる一枚。",
    tags: ["青", "孤独", "透明感", "静けさ"],
    defaultColor: { name: "瑠璃色", hex: "#1E50A2" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Marc,_Franz_-_Blue_Horse_I_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1911年",
    themeGroup: "青・孤独・静けさ",
    shareText: "青い馬の静けさに、澄んだ誰かを重ねる。",
    imagePath: "assets/images/painting_022_marc_blue_horse.jpg"
  },
  {
    contentId: "painting_023",
    type: "painting",
    title: "叫び",
    author: "エドヴァルド・ムンク",
    fragment: "空が歪み、声にならない声がひろがる。",
    shortComment: "内側の不安が、風景そのものになる一枚。",
    tags: ["不安", "叫び", "孤独", "夕暮れ"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Edvard_Munch_-_The_Scream_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1893年",
    themeGroup: "不安・孤独・夕暮れ",
    shareText: "声にならない叫びに、心の揺れを重ねる。",
    imagePath: "assets/images/painting_023_munch_the_scream.jpg"
  },
  {
    contentId: "painting_024",
    type: "painting",
    title: "マダムXの肖像",
    author: "ジョン・シンガー・サージェント",
    fragment: "黒いドレスの輪郭が、強く静かに立つ。",
    shortComment: "冷たい優雅さに、凛とした気配を重ねる一枚。",
    tags: ["凛とした", "黒", "まなざし", "静けさ"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sargent_MadameX.jpeg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1884年",
    themeGroup: "黒・肖像・凛とした",
    shareText: "黒い輪郭の静けさに、強い誰かを重ねる。",
    imagePath: "assets/images/painting_024_sargent_madame_x.jpg"
  },
  {
    contentId: "painting_025",
    type: "painting",
    title: "笠をかぶった自画像",
    author: "エリザベート＝ルイーズ・ヴィジェ＝ルブラン",
    fragment: "明るい視線が、こちらへやわらかく届く。",
    shortComment: "軽やかな自信と優雅さを重ねる肖像。",
    tags: ["まなざし", "光", "凛とした", "優雅"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Self-portrait_in_a_Straw_Hat_by_Elisabeth-Louise_Vigée-Lebrun.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1782年",
    themeGroup: "肖像・光・優雅",
    shareText: "明るいまなざしに、軽やかな誰かを重ねる。",
    imagePath: "assets/images/painting_025_vigee_le_brun_self_portrait.jpg"
  },
  {
    contentId: "painting_026",
    type: "painting",
    title: "真珠の首飾りの女",
    author: "ヨハネス・フェルメール",
    fragment: "小さな光の粒が、部屋の静けさを照らす。",
    shortComment: "日常の中の光に、ひそやかな美しさを重ねる一枚。",
    tags: ["光", "静けさ", "室内", "透明感"],
    defaultColor: { name: "胡粉色", hex: "#FFFFFC" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jan_Vermeer_van_Delft_013.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1664年頃",
    themeGroup: "室内・光・静けさ",
    shareText: "小さな光の粒に、ひそやかな誰かを重ねる。",
    imagePath: "assets/images/painting_026_vermeer_woman_with_pearl_necklace.jpg"
  },
  {
    contentId: "painting_027",
    type: "painting",
    title: "牛乳を注ぐ女",
    author: "ヨハネス・フェルメール",
    fragment: "静かな手元に、朝の光が集まる。",
    shortComment: "何気ない所作の中に、深い静けさを重ねる一枚。",
    tags: ["朝", "光", "静けさ", "日常"],
    defaultColor: { name: "生成色", hex: "#FBFAF5" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1658-1661年頃",
    themeGroup: "日常・朝・光",
    shareText: "静かな手元の光に、日常の誰かを重ねる。",
    imagePath: "assets/images/painting_027_vermeer_milkmaid.jpg"
  },
  {
    contentId: "painting_028",
    type: "painting",
    title: "ラス・メニーナス",
    author: "ディエゴ・ベラスケス",
    fragment: "視線が交差し、部屋そのものが謎になる。",
    shortComment: "誰が見て、誰に見られているのかを揺らす一枚。",
    tags: ["まなざし", "謎", "室内", "余白"],
    defaultColor: { name: "銀鼠", hex: "#AFAFB0" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Las_Meninas,_by_Diego_Velázquez,_from_Prado_in_Google_Earth.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1656年",
    themeGroup: "視線・室内・謎",
    shareText: "交差する視線に、謎めいた誰かを重ねる。",
    imagePath: "assets/images/painting_028_velazquez_las_meninas.jpg"
  },
  {
    contentId: "painting_029",
    type: "painting",
    title: "夜警",
    author: "レンブラント・ファン・レイン",
    fragment: "暗がりの中から、光を受けた人々が動き出す。",
    shortComment: "集団の中に差し込む光に、物語の気配を重ねる一枚。",
    tags: ["光", "影", "物語", "凛とした"],
    defaultColor: { name: "墨色", hex: "#2B2B2B" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_ronda_de_noche,_por_Rembrandt_van_Rijn.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1642年",
    themeGroup: "光・影・物語",
    shareText: "暗がりから動き出す光に、誰かの物語を重ねる。",
    imagePath: "assets/images/painting_029_rembrandt_night_watch.jpg"
  },
  {
    contentId: "painting_030",
    type: "painting",
    title: "窓辺で手紙を読む女",
    author: "ヨハネス・フェルメール",
    fragment: "窓の光が、読まれない心まで照らす。",
    shortComment: "手紙と沈黙の間に、遠い誰かを重ねる一枚。",
    tags: ["手紙", "光", "静けさ", "恋"],
    defaultColor: { name: "青磁", hex: "#A8C8B9" },
    source: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_-_Girl_Reading_a_Letter_by_an_Open_Window_-_Google_Art_Project.jpg",
    licenseNote: "Wikimedia Commons上のPublic Domain画像。",
    period: "1657-1659年頃",
    themeGroup: "手紙・光・静けさ",
    shareText: "窓辺の手紙に、遠い誰かの気配を重ねる。",
    imagePath: "assets/images/painting_030_vermeer_girl_reading_letter.jpg"
  }
];
const KASANE_COLORS = [
  { name: "桜色",  basic: "ピンク",  hex: "#FDEFF2" },
  { name: "薄紅",  basic: "ピンク",  hex: "#FADCE0" },
  { name: "生成色", basic: "ベージュ", hex: "#FBFAF5" },
  { name: "胡粉色", basic: "白",     hex: "#FFFFFC" },
  { name: "銀鼠",  basic: "グレー",  hex: "#AFAFB0" },
  { name: "墨色",  basic: "黒",     hex: "#2B2B2B" },
  { name: "瑠璃色", basic: "青",     hex: "#1E50A2" },
  { name: "浅葱色", basic: "青緑",   hex: "#00A3AF" },
  { name: "藤色",  basic: "紫",     hex: "#BBBCDE" },
  { name: "青磁",  basic: "青緑",   hex: "#A8C8B9" },
  { name: "紅色",  basic: "赤",     hex: "#C22047" },
  { name: "朱色",  basic: "赤橙",   hex: "#EB6101" },
  { name: "山吹色", basic: "黄",     hex: "#F8B500" },
  { name: "若草色", basic: "緑",     hex: "#C3D825" },
  { name: "常磐色", basic: "緑",     hex: "#007B43" },
  { name: "空色",  basic: "水色",   hex: "#A0D8EF" },
  { name: "藍色",  basic: "青",     hex: "#165E83" },
  { name: "菫色",  basic: "紫",     hex: "#7058A3" },
  { name: "葡萄色", basic: "紫",     hex: "#522F60" },
  { name: "煤竹色", basic: "茶",     hex: "#5D5245" }
];
